import json
import pandas as pd
import glob
import os
import argparse
from datetime import datetime


def format_sales(amount):
    return f"{amount / 100000000:.1f}억원"


def format_price(price):
    return f"₩{int(price):,}"


def get_growth_icon(rate):
    if rate > 0.5:
        return "🚀"
    if rate > 0:
        return "📈"
    return "📉"


def generate_markdown_report(data, output_dir):
    brand_name = data["brand"]
    date_str = datetime.now().strftime("%Y-%m-%d")

    # Sort products by rank
    sorted_products = sorted(data["products"], key=lambda x: x["순위"])

    md_content = f"""# {brand_name} 판매 분석 리포트
**분석일**: {date_str}

## 1. 브랜드별 매출 현황
| 브랜드 | 매출 | 점유율 | 비고 |
| ------ | ---- | ------ | ---- |
| **{brand_name}** | **{format_sales(data["total_sales"])}** | **{data["share"]:.1f}%** | **{data["position"]}** |

## 2. {brand_name} BEST 10 상품
| 순위 | 품명 | TAG가 | 판매수량 | 판매금액 | 전주대비 | 할인율 |
|------|------|-------|---------|----------|----------|--------|
"""

    for p in sorted_products:
        growth_pct = p["전주대비"] * 100
        growth_str = f"{'+' if growth_pct > 0 else ''}{growth_pct:.1f}%"
        discount_pct = p["전체할인율"] * 100
        md_content += f"| {p['순위']} | {p['품명']} | {format_price(p['TAG가'])} | {int(p['판매수량']):,}개 | {format_sales(p['판매금액'])} | {growth_str} | {discount_pct:.1f}% |\n"

    md_content += f"""
## 3. 채널별 매출
- **오프라인**: {format_sales(data["channels"]["offline"]["amount"])} ({data["channels"]["offline"]["ratio"]:.1f}%)
- **온라인**: {format_sales(data["channels"]["online"]["amount"])} ({data["channels"]["online"]["ratio"]:.1f}%)
- **면세점**: {format_sales(data["channels"]["dutyfree"]["amount"])} ({data["channels"]["dutyfree"]["ratio"]:.1f}%)

## 4. 카테고리별 분석
| 카테고리 | 매출 비중 | 판매수량 |
|----------|----------|----------|
"""
    total_sales = data["total_sales"]
    for cat, val in data["categories"].items():
        ratio = (val["판매금액"] / total_sales) * 100
        md_content += f"| {cat} | {ratio:.1f}% | {int(val['판매수량']):,}개 |\n"

    md_content += "\n## 5. 전주 대비 변화\n### 성장 상품\n"
    for item in data["growth_items"][:4]:
        rate = item["전주대비"] * 100
        md_content += f"- {get_growth_icon(item['전주대비'])} **{item['품명']}**: **{'+' if rate > 0 else ''}{rate:.1f}%**\n"

    md_content += "\n### 하락 상품\n"
    for item in data["decline_items"][:4]:
        rate = item["전주대비"] * 100
        md_content += f"- 📉 {item['품명']}: {rate:.1f}%\n"

    # Insights placeholder - In a real scenario, this could be generated by LLM or simple rule-based logic
    md_content += """
## 6. 핵심 인사이트
- **매출 요약**: 시장 점유율 및 채널 비중 기반 현황 요약.
- **상품 트렌드**: 급성장 상품 및 하락세 상품군 식별.
- **전략 제언**: 채널별/카테고리별 개선 포인트 도출 필요.
"""

    filename = f"sales_report_{brand_name}_{date_str.replace('-', '')}.md"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(md_content)

    return filepath


def generate_excel_dashboard(json_files, output_path):
    kpi_rows = []
    best10_rows = []
    channel_rows = []
    category_rows = []
    trends_rows = []

    brand_map = {"커버낫": "covernat", "리(LEE)": "lee", "와키윌리": "wackywilly"}

    for json_file in json_files:
        with open(json_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        brand_kr = data["brand"]
        brand_code = brand_map.get(brand_kr, brand_kr)

        # KPI
        total_qty = sum(cat["판매수량"] for cat in data["categories"].values())
        kpi_rows.append(
            {
                "Brand": brand_code,
                "Sales": data["total_sales"],
                "Sales_Str": format_sales(data["total_sales"]),
                "Share": f"{data['share']:.1f}%",
                "Qty": f"{int(total_qty):,}",
                "Discount": f"{data['avg_discount'] * 100:.1f}%",
                "DiscountNote": "High"
                if data["avg_discount"] > 0.35
                else ("Low" if data["avg_discount"] < 0.3 else "Mid"),
            }
        )

        # Best 10
        for idx, prod in enumerate(data["products"]):
            growth = prod["전주대비"] * 100
            best10_rows.append(
                [
                    brand_code,
                    idx + 1,
                    prod["품명"],
                    f"{int(prod['TAG가']):,}",
                    f"{prod['판매금액'] / 100000000:.2f}억",
                    f"{'+' if growth > 0 else ''}{growth:.1f}%",
                ]
            )

        # Channel
        channel_rows.append(
            {
                "Brand": brand_code,
                "Offline_Pct": round(data["channels"]["offline"]["ratio"], 1),
                "Online_Pct": round(data["channels"]["online"]["ratio"], 1),
                "DutyFree_Pct": round(data["channels"]["dutyfree"]["ratio"], 1),
            }
        )

        # Category
        cat_mapping = {
            "아우터(다운/점퍼)": "Outer",
            "상의(후드/맨투맨)": "Top",
            "티셔츠": "T-Shirts",
            "니트": "Knit",
        }
        for cat, val in data["categories"].items():
            pct = (val["판매금액"] / data["total_sales"]) * 100
            category_rows.append([brand_code, cat_mapping.get(cat, cat), round(pct, 1)])

        # Trends
        for item in data["growth_items"][:3]:
            trends_rows.append(
                [brand_code, "Growth", item["품명"], f"+{item['전주대비'] * 100:.1f}%"]
            )
        for item in data["decline_items"][:3]:
            trends_rows.append(
                [brand_code, "Decline", item["품명"], f"{item['전주대비'] * 100:.1f}%"]
            )

    # Sort KPI for Rank
    kpi_rows.sort(key=lambda x: x["Sales"], reverse=True)
    for i, row in enumerate(kpi_rows):
        row["Rank"] = f"Rank #{i + 1}"

    df_kpi = pd.DataFrame(kpi_rows)[
        ["Brand", "Sales_Str", "Share", "Rank", "Qty", "Discount", "DiscountNote"]
    ]
    df_kpi.columns = [
        "Brand",
        "Sales",
        "Share",
        "Rank",
        "Qty",
        "Discount",
        "DiscountNote",
    ]

    # Insights (Template)
    insights_data = [
        [
            "market",
            "Season Transition",
            "모든 브랜드에서 헤비 아우터 매출 둔화가 관측됨. 베스트, 하프집업, 경량 아우터 등 간절기 아이템으로 수요가 빠르게 이동 중.",
        ],
        [
            "market",
            "Offline Reliance",
            "커버낫(75%)과 와키윌리(66%)는 여전히 오프라인 채널 의존도가 높음. 디지털 전환(D2C 강화)이 시장 전체의 핵심 과제로 대두.",
        ],
        [
            "market",
            "Duty Free Recovery",
            "리(Lee)가 면세 채널 점유율 36%로 인바운드 관광 회복세를 선도 중. 타 브랜드들도 트래블 리테일 전략 강화가 필요한 시점.",
        ],
        [
            "covernat",
            "Market Dominance",
            "45.7%의 압도적 점유율로 1위 유지. 오프라인(74.8%)이 성장을 주도.",
        ],
        [
            "lee",
            "Brand Power",
            "가장 낮은 할인율(27.2%)로 강력한 브랜드 가치와 가격 방어력 입증.",
        ],
        [
            "wackywilly",
            "IP Differentiation",
            "키키 캐릭터 아이템(후드 +21%, 스웻 +7%)이 성장을 주도하며 차별화 성공.",
        ],
    ]
    df_insights = pd.DataFrame(insights_data, columns=["Brand", "Title", "Description"])

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        df_kpi.to_excel(writer, sheet_name="KPI", index=False)
        pd.DataFrame(
            best10_rows,
            columns=[
                "Brand",
                "Rank",
                "ProductName",
                "Price",
                "SalesAmount",
                "GrowthRate",
            ],
        ).to_excel(writer, sheet_name="Best10", index=False)
        pd.DataFrame(channel_rows).to_excel(writer, sheet_name="Channel", index=False)
        pd.DataFrame(
            category_rows, columns=["Brand", "CategoryName", "Percentage"]
        ).to_excel(writer, sheet_name="Category", index=False)
        pd.DataFrame(
            trends_rows, columns=["Brand", "Type", "ProductName", "Value"]
        ).to_excel(writer, sheet_name="Trends", index=False)
        df_insights.to_excel(writer, sheet_name="Insights", index=False)

    return output_path


def main():
    parser = argparse.ArgumentParser(description="Weekly Report Generator")
    parser.add_argument(
        "--input_dir",
        required=True,
        help="Directory containing brand_analysis_*.json files",
    )
    args = parser.parse_args()

    json_files = glob.glob(os.path.join(args.input_dir, "brand_analysis_*.json"))
    if not json_files:
        print("No analysis files found.")
        return

    print(f"Found {len(json_files)} analysis files.")

    # 1. Generate Markdown Reports
    for f in json_files:
        with open(f, "r", encoding="utf-8") as json_f:
            data = json.load(json_f)
            md_path = generate_markdown_report(data, args.input_dir)
            print(f"Generated Report: {md_path}")

    # 2. Generate Excel Dashboard Data
    excel_path = os.path.join(args.input_dir, "weekly_data_template.xlsx")
    generate_excel_dashboard(json_files, excel_path)
    print(f"Generated Dashboard Data: {excel_path}")


if __name__ == "__main__":
    main()
